// <auto-generated />
using System;
using DVLD.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVLD.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516225744_AddCreatedByUserIdToPerson")]
    partial class AddCreatedByUserIdToPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DVLD.DataAccess.Entities.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("ApplicantPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("DATETIME");

                    b.Property<byte>("ApplicationStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("ApplicationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastStatusDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("PaidFees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicantPersonId");

                    b.HasIndex("ApplicationTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.ApplicationType", b =>
                {
                    b.Property<int>("ApplicationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationTypeId"));

                    b.Property<decimal>("Fees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ApplicationTypeId");

                    b.ToTable("ApplicationTypes");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.DetainedLicense", b =>
                {
                    b.Property<int>("DetainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetainId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetainDate")
                        .HasColumnType("DATETIME");

                    b.Property<decimal>("FineFees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("BIT");

                    b.Property<int>("LicenseId")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseApplicationId")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("DATETIME");

                    b.HasKey("DetainId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("ReleaseApplicationId")
                        .IsUnique()
                        .HasFilter("[ReleaseApplicationId] IS NOT NULL");

                    b.HasIndex("ReleaseByUserId");

                    b.ToTable("DetainedLicenses");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.InternationalLicense", b =>
                {
                    b.Property<int>("InternationalLicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternationalLicenseId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("IssuedUsingLocalLicenseId")
                        .HasColumnType("int");

                    b.HasKey("InternationalLicenseId");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DriverId");

                    b.HasIndex("IssuedUsingLocalLicenseId");

                    b.ToTable("InternationalLicenses");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("DATETIME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("DATETIME");

                    b.Property<byte>("IssueReason")
                        .HasColumnType("tinyint");

                    b.Property<int>("LicenseClassId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PaidFees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("LicenseId");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DriverId");

                    b.HasIndex("LicenseClassId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.LicenseClass", b =>
                {
                    b.Property<int>("LicenseClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseClassId"));

                    b.Property<string>("ClassDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ClassFees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("DefaultValidityLength")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("MinimumAllowedAge")
                        .HasColumnType("TINYINT");

                    b.HasKey("LicenseClassId");

                    b.ToTable("LicenseClasses");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.LocalDrivingLicenseApplication", b =>
                {
                    b.Property<int>("LocalDrivingLicenseApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalDrivingLicenseApplicationId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("LicenseClassId")
                        .HasColumnType("int");

                    b.HasKey("LocalDrivingLicenseApplicationId");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("LicenseClassId");

                    b.ToTable("LocalDrivingLicenseApplications");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NationalityCountryId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NationalNo")
                        .IsUnique();

                    b.HasIndex("NationalityCountryId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TestAppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("TestResult")
                        .HasColumnType("BIT");

                    b.HasKey("TestId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TestAppointmentId")
                        .IsUnique();

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.TestAppointment", b =>
                {
                    b.Property<int>("TestAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestAppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("BIT");

                    b.Property<int>("LocalDrivingLicenseApplicationId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidFees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("RetakeTestApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("int");

                    b.HasKey("TestAppointmentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LocalDrivingLicenseApplicationId");

                    b.HasIndex("RetakeTestApplicationId")
                        .IsUnique()
                        .HasFilter("[RetakeTestApplicationId] IS NOT NULL");

                    b.HasIndex("TestTypeId");

                    b.ToTable("TestAppointments");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.TestType", b =>
                {
                    b.Property<int>("TestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Fees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TestTypeId");

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Application", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.Person", "ApplicantPerson")
                        .WithMany()
                        .HasForeignKey("ApplicantPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.ApplicationType", "ApplicationType")
                        .WithMany()
                        .HasForeignKey("ApplicationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantPerson");

                    b.Navigation("ApplicationType");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.DetainedLicense", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.License", "License")
                        .WithMany("DetainedLicenses")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.Application", "ReleaseApplication")
                        .WithOne()
                        .HasForeignKey("DVLD.DataAccess.Entities.DetainedLicense", "ReleaseApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD.DataAccess.Entities.User", "ReleaseByUser")
                        .WithMany()
                        .HasForeignKey("ReleaseByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("License");

                    b.Navigation("ReleaseApplication");

                    b.Navigation("ReleaseByUser");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Driver", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.Person", "Person")
                        .WithOne("Driver")
                        .HasForeignKey("DVLD.DataAccess.Entities.Driver", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.InternationalLicense", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.Application", "Application")
                        .WithOne("InternationalLicense")
                        .HasForeignKey("DVLD.DataAccess.Entities.InternationalLicense", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.LocalDrivingLicenseApplication", "IssuedUsingLocalLicense")
                        .WithMany()
                        .HasForeignKey("IssuedUsingLocalLicenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Driver");

                    b.Navigation("IssuedUsingLocalLicense");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.License", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.Application", "Application")
                        .WithOne("License")
                        .HasForeignKey("DVLD.DataAccess.Entities.License", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.Driver", "Driver")
                        .WithMany("Licenses")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.LicenseClass", "LicenseClass")
                        .WithMany()
                        .HasForeignKey("LicenseClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Driver");

                    b.Navigation("LicenseClass");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.LocalDrivingLicenseApplication", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.Application", "Application")
                        .WithOne("LocalDrivingLicenseApplication")
                        .HasForeignKey("DVLD.DataAccess.Entities.LocalDrivingLicenseApplication", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.LicenseClass", "LicenseClass")
                        .WithMany()
                        .HasForeignKey("LicenseClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("LicenseClass");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Person", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.Country", "Country")
                        .WithMany("People")
                        .HasForeignKey("NationalityCountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Test", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.TestAppointment", "TestAppointment")
                        .WithOne("Test")
                        .HasForeignKey("DVLD.DataAccess.Entities.Test", "TestAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("TestAppointment");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.TestAppointment", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.LocalDrivingLicenseApplication", "LocalDrivingLicenseApplication")
                        .WithMany("TestAppointments")
                        .HasForeignKey("LocalDrivingLicenseApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.DataAccess.Entities.Application", "RetakeTestApplication")
                        .WithOne()
                        .HasForeignKey("DVLD.DataAccess.Entities.TestAppointment", "RetakeTestApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DVLD.DataAccess.Entities.TestType", "TestType")
                        .WithMany()
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("LocalDrivingLicenseApplication");

                    b.Navigation("RetakeTestApplication");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.User", b =>
                {
                    b.HasOne("DVLD.DataAccess.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("DVLD.DataAccess.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Application", b =>
                {
                    b.Navigation("InternationalLicense");

                    b.Navigation("License");

                    b.Navigation("LocalDrivingLicenseApplication");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Country", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Driver", b =>
                {
                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.License", b =>
                {
                    b.Navigation("DetainedLicenses");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.LocalDrivingLicenseApplication", b =>
                {
                    b.Navigation("TestAppointments");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.Person", b =>
                {
                    b.Navigation("Driver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DVLD.DataAccess.Entities.TestAppointment", b =>
                {
                    b.Navigation("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
